### PR TITLE
Site Updates Jan-Mar 2017

### PR DESCRIPTION
**Pull request by daniel-swain**
This PR includes the following updates:
- Added Bradley & Daniel Team Profiles to the homepage
- Updated Blog Post style
- Updated Blog index style
- Added "Shopify Sections" blog post

### CODE REVIEW

**Comment by daniel-swain** [comment]
- Updated team section
http://d.pr/i/pBr6

- Updated blog index
http://d.pr/i/OmXe

- Shopify Sections post
http://d.pr/i/jMxI
http://d.pr/i/bKH2
http://d.pr/i/Qbb0
http://d.pr/i/OYSz
http://d.pr/i/4SL4

**Comment by roblingle** [comment]
Looks good. I'd like to edit the blog post text before we push and have @steve-ross do a quick technical review.

I noticed a few changes around bootstrap columns, have we tested the changes on tablet and mobile yet?

**Comment by daniel-swain** [comment]
The ourskinny logo is a bit big on mobile, but looks fine on tablet:
screen shot on 2017-03-03 at 11 50 17
Fig.1 Mobile Logos


screen shot on 2017-03-03 at 12 01 02
Fig.2 Tablet Logos

**Comment by roblingle** [comment]
@daniel-swain Agree. We should shrink the OurSkinny logo down some.

**Pull request merged**
